#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Thu Oct 02 02:48:20 JST 2025
maven-metadata-github.xml.error=
maven-metadata-github.xml.lastUpdated=1759340900066
