#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Mon Oct 28 20:27:22 JST 2024
maven-metadata-internal.repo.xml.lastUpdated=1726767576468
maven-metadata-tamacat.org.xml.error=
maven-metadata-tamacat.org.xml.lastUpdated=1730114842740
