#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Nov 12 22:59:10 JST 2024
maven-metadata-central.xml.error=
maven-metadata-central.xml.lastUpdated=1731419950572
maven-metadata-internal.repo.xml.lastUpdated=1726767576601
maven-metadata-tamacat.org.xml.error=
maven-metadata-tamacat.org.xml.lastUpdated=1731419950570
