#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Fri Sep 20 02:39:20 JST 2024
maven-metadata-internal.repo.xml.lastUpdated=1726767560352
